### ISSUE TITLE
Ninja mingw build not recognising changes to tag on first build after change

### ISSUE THREAD

**Issue by davepregan** [nocnokneo/cmake-git-versioning-example#2]
I am on a Windows system and am interested in this code for versioning a cross-compiled embedded project.
I am using Git for Windows and Git Bash.
If I generate for "Unix Makefiles" everything works as I expect. I can delete a tag,  build and run; add a tag, build and run correctly. The changes are immediately detected. 
If I generate for Ninja on the first build it is correct. If I then modify the tag and build, the changes are written to foobar_version.h, but the build stops after that step. If I build again all the build steps are executed and give the expected result.

Any ideas how to correct this. I would prefer to use ninja because of the speed advantage

**Comment by nocnokneo** [comment]
Hard to say without more specifics.

> If I then modify the tag and build, the changes are written to foobar_version.h, but the build stops after that step

When you say "build" do you mean build the default target? (i.e. by simply running `ninja`)

It could be that you have a target that is missing a dependency on the `version` target. For example if you have a library `mylib` that depends on the foobar_version.h header then you should have `add_dependencies(mylib version)`

**Comment by davepregan** [comment]
When I say build I mean running ninja or make after having modified/deleted tags using a Git Bash shell. For a "Unix Makefiles" generator it seems to work as expected. For the ninja generator foobar_version.h is modified on the 'ninja' but this does not cause a relink, a second 'ninja' picks up the fact that foobar_version.h has changed and relinks.
Someone from Kitware told me that this was because of how ninja collects it dep file information. He pointed me to this project https://github.com/Kitware/sprokit/blob/master/src/sprokit/CMakeLists.txt which is huge.
I got something working using add_custom_command

Thank you very much for replying

**Comment by nocnokneo** [comment]
Glad you found a solution!
